### ISSUE TITLE
problem with commonjs / mdx-js in large pnpm monorepo

### ISSUE THREAD

**Issue by grmkris** [wevm/vocs#19]
I tried installing vocs into a relatively big monorepo using pnpm, and i get the following error when trying to run it:

potential causes:
- using docusaurus already in one of the packages in the monorepo
- using commonjs in the monorepo

Thanks for the help in advance, vocs looks really awesome and I'd love to start using it

```
failed to load config from.  ..../.pnpm/vocs@1.0.0-alpha.10_@types+react@18.2.47_react-dom@18.2.0_react@18.2.0_rollup@4.9.4_typescript@5.3.3/node_modules/vocs/_lib/vite/vite.config.js
file://...././node_modules/.pnpm/vocs@1.0.0-alpha.10_@types+react@18.2.47_react-dom@18.2.0_react@18.2.0_rollup@4.9.4_typescript@5.3.3/node_modules/vocs/_lib/vite/vite.config.js.timestamp-1705231816407-297d2eceaadbe.mjs:1076
import { compile, run } from "file:///...././node_modules/.pnpm/@mdx-js+mdx@1.6.22/node_modules/@mdx-js/mdx/index.js";
         ^^^^^^^
SyntaxError: Named export 'compile' not found. The requested module 'file:///...././node_modules/.pnpm/@mdx-js+mdx@1.6.22/node_modules/@mdx-js/mdx/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file:///..../.node_modules/.pnpm/@mdx-js+mdx@1.6.22/node_modules/@mdx-js/mdx/index.js';
const { compile, run } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadConfigFromBundledFile (file:///...././node_modules/.pnpm/vite@5.0.11/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:68380:21)
    at async loadConfigFromFile (file:///...././node_modules/.pnpm/vite@5.0.11/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:68237:28)
    at async resolveConfig (file:///...././node_modules/.pnpm/vite@5.0.11/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:67838:28)
    at async _createServer (file:///U..../.node_modules/.pnpm/vite@5.0.11/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:60327:20)
    at async CAC.dev (file:///...././node_modules/.pnpm/vocs@1.0.0-alpha.10_@types+react@18.2.47_react-dom@18.2.0_react@18.2.0_rollup@4.9.4_typescript@5.3.3/node_modules/vocs/_lib/cli/commands/dev.js:6:20)

Node.js v20.9.0
 ELIFECYCLE  Command failed with exit code 1.
(⎈|)➜  documentation git:(boostrap-internal-docs-using-vocs) ✗ 

```

**Comment by jxom** [comment]
At first glance, it looks like it's trying to pull in the `@mdx-js/mdx` library at v1.6.22. However, Vocs uses v3. 

Can you try `1.0.0-alpha.11`? We included `@mdx-js/mdx` into the dependencies, so hopefully it pulls in our version now instead.

**Comment by grmkris** [comment]
oh yes that's fine actually

**Comment by grmkris** [comment]
ah didn't work :( i think this is problem with pnpm where it installs just one version of the library (current docusaurus uses mdx 1.*

**Comment by grmkris** [comment]
solution:
```
"dependencies": {
    "react": "latest",
    "react-dom": "latest",
    "vocs": "latest",
    "@mdx-js/mdx": "^3.0.0"
  }
```

**Comment by W3stside** [comment]
Re-opening this via my issue, lerna monorepo and issues here with commonjs and `vite` + `yaml` import. Solution below error.

```bash
$ vocs dev
failed to load config from /Users/davidsato/Work/pastelle/monorepo/node_modules/vocs/_lib/vite/vite.config.js
file:///Users/davidsato/Work/pastelle/monorepo/node_modules/vocs/_lib/vite/vite.config.js.timestamp-1706294783457-415083134ef1c.mjs:1579
import { parse } from "file:///Users/davidsato/Work/pastelle/monorepo/node_modules/yaml/index.js";
         ^^^^^
SyntaxError: Named export 'parse' not found. The requested module 'file:///Users/davidsato/Work/pastelle/monorepo/node_modules/yaml/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file:///Users/davidsato/Work/pastelle/monorepo/node_modules/yaml/index.js';
const { parse } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadConfigFromBundledFile (file:///Users/davidsato/Work/pastelle/monorepo/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68383:21)
    at async loadConfigFromFile (file:///Users/davidsato/Work/pastelle/monorepo/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68240:28)
    at async resolveConfig (file:///Users/davidsato/Work/pastelle/monorepo/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:67841:28)
    at async _createServer (file:///Users/davidsato/Work/pastelle/monorepo/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:60327:20)
    at async CAC.dev (file:///Users/davidsato/Work/pastelle/monorepo/node_modules/vocs/_lib/cli/commands/dev.js:6:20)

Node.js v21.1.0
error Command failed with exit code 1.
```

## Solution
1. install `vite` latest
2. install `yaml` latest
3. (optional) change `vocs.config.ts` to `vocs.config.mjs`

**Comment by mhpaler** [comment]
For pnpm & turborepo:

Add vite and yaml to workspace
```
pnpm add vite@latest yaml@latest -w
```

in workspace root package.json
```
  "pnpm": {
    "overrides": {
      "yaml": "2.4.5" <-- latest version of yaml
    }
  },
```
run install again...
```
pnpm install
```
